//this component holds all actions related to tasks
export const taskActions = {
    CREATE_TASK: "CREATE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    COMPLETE_TASK: "COMPLETE_TASK",
    FETCH_TASKS_REQUEST: "FETCH_USERS_REQUEST",
    FETCH_TASKS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_TASKS_FAILURE: "FETCH_USERS_FAILURE"
}