//this component holds all actions related to tasks
export const taskActions = {
    CREATE_TASK: "CREATE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    COMPLETE_TASK: "COMPLETE_TASK",
    FETCH_TASKS_REQUEST: "FETCH_TASKS_REQUEST",
    FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
    FETCH_TASKS_FAILURE: "FETCH_TASKS_FAILURE",
    ADD_TASK_REQUEST: "ADD_TASK_REQUEST",
    ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
    ADD_TASK_FAILURE: "ADD_TASK_FAILURE",
}